(defun color-theme-pmr ()
  (interactive)
  (color-theme-install
   '(color-theme-pmr
      ((border-color . "#d6d1d1")
      (cursor-color . "#333333")
      (foreground-color . "#000000")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "white" :background "black"))))
     (region ((t (:background "#d6dbf0"))))
     (font-lock-builtin-face ((t (:foreground "#d04343"))))
     (font-lock-comment-face ((t (:foreground "#44a74d"))))
     (font-lock-function-name-face ((t (:foreground "#000000"))))
     (font-lock-keyword-face ((t (:foreground "DeepSkyBlue4" :bold t))))
     (font-lock-string-face ((t (:foreground "#e31616"))))
     (font-lock-type-face ((t (:foreground"#ce6122"))))
     (font-lock-variable-name-face ((t (:foreground "#000000"))))
     (minibuffer-prompt ((t (:foreground "DeepSkyBlue4" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     (show-paren-match-face ((t (:background "LightGoldenrod1"))))
     (magit-item-highlight ((t (:background "gray98"))))
     (magit-diff-add ((t (:foreground "green" :bold t))))
     (isearch ((t (:foreground "white" :background "DarkOrange1"))))
     )))
(provide 'color-theme-pmr)