call pathogen#infect()

set nocompatible
let mapleader=","

set visualbell
set title

set wildmenu
set wildmode=longest:full
set wildignore=*.cm*,*.annot,*.o

filetype on
filetype plugin indent on
syntax on

set expandtab
set tabstop=8

set shiftwidth=2
set shiftround
set textwidth=0
set nowrap

set hidden

set showmatch

set ignorecase
set smartcase

set hlsearch
set incsearch
nmap <silent> ,/ :nohlsearch<CR>

imap jj <ESC>

colors xoria256
