set visualbell

set wildmenu
set wildmode=longest:full
set wildignore=*.cm*,*.annot,*.o

filetype on
filetype plugin indent on
syntax on

set expandtab
set tabstop=8

set shiftwidth=2

set hlsearch
set incsearch

imap jj <ESC>
