(deftheme monotonic "")
(custom-theme-set-faces
  'monotonic
  '(default ((t (:background "#ffffff" :foreground "#000000" ))))
'(font-lock-builtin-face ((t (:foreground "#4a4a4a" :weight semi-bold ))))
'(font-lock-comment-face ((t (:foreground "#4a0000" :weight normal ))))
'(compilation-error ((t (:foreground "#4a0000" ))))
'(compilation-info ((t (:foreground "#00004a" ))))
'(font-lock-constant-face ((t (:foreground "#000000" :weight normal ))))
'(cursor ((t (:foreground "#000000" ))))
'(font-lock-doc-face ((t (:foreground "#4a0000" :weight normal ))))
'(eshell-prompt ((t (:foreground "#4a4a4a" :weight semi-bold ))))
'(font-lock-function-name-face ((t (:foreground "#000000" :weight normal ))))
'(highlight ((t (:background "#eaeaea" ))))
'(font-lock-keyword-face ((t (:foreground "#4a4a4a" :weight semi-bold ))))
'(match ((t (:background "#ffec8b" :weight bold :foreground "#4a4a4a" ))))
'(isearch ((t (:background "#ffec8b" :weight bold :foreground "#4a4a4a" ))))
'(isearch-fail ((t (:background "#7f007f" :foreground "#ffffff" ))))
'(mode-line ((t (:background "#4a4a4a" :foreground "#ffffff" ))))
'(mode-line-inactive ((t (:background "#ebebeb" :foreground "#858585" ))))
'(lazy-highlight ((t (:background "#eaeaea" :weight bold ))))
'(org-done ((t (:foreground "#004a00" ))))
'(org-todo ((t (:foreground "#4a0000" ))))
'(show-paren-match ((t (:background "#ffec8b" ))))
'(show-paren-mismatch ((t (:background "#7f007f" :foreground "#ffffff" ))))
'(font-lock-preprocessor-face ((t (:foreground "#000000" :weight normal ))))
'(minibuffer-prompt ((t (:foreground "#4a4a4a" :weight semi-bold ))))
'(region ((t (:background "#eaeaea" ))))
'(font-lock-string-face ((t (:foreground "#4a0000" :weight normal ))))
'(tuareg-font-lock-governing-face ((t (:foreground "#4a4a4a"
                                       :weight semi-bold ))))
'(tuareg-font-lock-operator-face ((t (:foreground "#000000" :weight normal ))))
'(font-lock-type-face ((t (:foreground "#000000" :weight normal ))))
'(font-lock-variable-name-face ((t (:foreground "#000000" :weight normal ))))

  )
(provide-theme 'monotonic)
