(autoload 'w3m "w3m" "Interface for w3m on Emacs." t)
(add-hook 'w3m-mode-hook '(lambda ()
  ;; (set-face-foreground 'w3m-anchor-face "CadetBlue")
  ;; (set-face-foreground 'w3m-arrived-anchor-face "SeaGreen3")
  ;; (set-face-foreground 'w3m-image-face "burlywood")
  ;; (set-face-foreground 'w3m-header-line-location-title-face "goldenrod")
  (setq w3m-fill-column 72)))
